### ISSUE TITLE
Master branch of ttrss?

### ISSUE THREAD

**Issue by kierun** [naeramarth7/clean-greader#11]
Can I use this theme with the master branch ttrss? Does the version parameter need to be the last git hash?

**Comment by naeramarth7** [comment]
In general: This theme should be usable with the master branch of tt-rss. Though, tt-rss checks the css files for an `supports-version` tag at the beginning of a css file and only accepts styles, that match the current version (no semver or anything, afaik).

Just updated it to `/* supports-version:16.1 */` to match the latest tt-rss release. If you can't wait to use it on tt-rss `16.2`, as soon as it gets published, you can just update the version string in [clean-greader.css#L1](https://github.com/naeramarth7/clean-greader/blob/master/clean-greader.css#L1). See [include/version.php#L2](https://tt-rss.org/gitlab/fox/tt-rss/blob/master/include/version.php#L2) for the current tt-rss version.

**Comment by kierun** [comment]
Super, this worked great. Many thanks indeed.
