### ISSUE TITLE
Loading, please wait

### ISSUE THREAD

**Issue by bonelifer** [naeramarth7/clean-greader#6]
Now using the suggested git update method by Fox. I get "Loading, please wait..." and it never goes away, unless I switch to default theme.

**Comment by naeramarth7** [comment]
Can't reproduce. Just upgraded to [4ca621a3](https://github.com/gothfox/Tiny-Tiny-RSS/commit/4ca621a36016de1fbb5447e1c1de0b607ba94a7c) and everything's fine.

Though, I can't imagine the loop on the loading screen has anything to do with the theme -- what's the "suggested git update method"?

**Comment by bonelifer** [comment]
ie, using git instead of Fox releasing pre-packaged archives

**Comment by bonelifer** [comment]
On current version of both tt-rss and clean-greader.

bash file I use:
```
## http://tt-rss.org/forum/viewtopic.php?p=19396
DATE=`date +"%m-%d-%Y"`

cd /var/www/apps/
sudo mv reader/ reader-old-$DATE/

sudo git clone https://github.com/gothfox/Tiny-Tiny-RSS.git ./reader
sudo cp ./reader-old-$DATE/feed-icons/*.ico ./reader/feed-icons/
sudo cp ./reader-old-$DATE/config.php ./reader/

sudo chmod -R 777 ./reader/cache/images
sudo chmod -R 777 ./reader/cache/upload
sudo chmod -R 777 ./reader/cache/export
sudo chmod -R 777 ./reader/cache/js
sudo chmod -R 777 ./reader/feed-icons
sudo chmod -R 777 ./reader/lock

# Install clean-greader theme
cd /var/www/apps/reader/themes
sudo git clone https://github.com/naeramarth7/clean-greader.git
sudo ln -s ./clean-greader/clean-greader.css ./clean-greader.css
```

I completely deleted my Firefox cache and the cookies for my ttrss instance.

**Comment by naeramarth7** [comment]
This seems like a general problem with your setup, not with the theme itself. However...

So I guess you're coming from the pre-packed version and have to use the git version now?

First of all, you should **never** do this using the root user!
Try:

    cd /var/www/apps
    git clone https://github.com/gothfox/Tiny-Tiny-RSS.git ./reader

If you're not able to do this without using root privilegs, you're server may be misconfigured.
First of all check the permissions on your /var/www folder. It should say something like this:

    total 12
    drwsrwsr-x  3 www-data www-data 4096 Feb 13 07:30 .
    drwxr-xr-x 14 root     root     4096 Feb 13 07:01 ..
    drwxrwsr-x 20 vagrant  www-data 4096 Feb 13 07:31 html

The second line tells us, www-data is the group you need to be in, so add yourself to the group.

    sudo adduser $USER www-data

Log out of the ssh session and back in. Then make sure, the permissions are applied to all folders within `/var/www` -- for existing and new folders.

    sudo chmod 0755 -R /var/www
    sudo chmod g+s -R /var/www

Now clone the repos and copy your config.php over -- no need to set the permissions for cache folder anymore.

BTW: For further updates, all you need to do is:

    cd /var/www/apps/reader
    git pull

If you're still having issues, please contact me via mail, so I might help you setting this up (:

**Comment by bonelifer** [comment]
I'm on Ubuntu. Your suggestion, just caused ttrss to give a page that tells you to set these directories to 777 page. So I looked online and found: 
chown -R www-data:www-data reader/

Which worked.  But still your theme has the same problem. I guess I'll go with either the default theme or the feedly theme(neither of which have this problem). This is ridiculous.

**Comment by billt2006** [comment]
I am seeing this as well and it is absolutely a theme issue. If you look in the default.css `#notify` should only be shown if it has the `.visible` class. This is **not** included in clean-greader.css.

**Comment by naeramarth7** [comment]
@billt2006 Thanks, guess a screenshot (or better description) would have helped a lot, since I was looking for an issue on the loading screen which also says "*Loading, please wait...*".

**Comment by naeramarth7** [comment]
@billt2006 Though, as I can not reproduce this with loading feed, could you provide a screen, where this happens on your tt-rss instance? Thanks.

**Comment by bonelifer** [comment]
Screenshot: http://postimg.org/image/rryz894j3/

**Comment by billt2006** [comment]
Ah that makes sense. It happens on the main screen in tt-rss.

![notify](https://cloud.githubusercontent.com/assets/3450688/6189238/280d07e0-b367-11e4-8788-1b386e4ab853.png)

I've been seeing it for a while and had planned to fix it, but it just hasn't bugged me enough to bother. :smile:

**Comment by billt2006** [comment]
:+1:
