### ISSUE TITLE
feed icons are gone with recent ttrss update

### ISSUE THREAD

**Issue by maxfragg** [naeramarth7/clean-greader#7]
there are no generic feed icons anymore when using the most recent TTRSS ( 1.15.3 ), it happens in all browsers

**Comment by naeramarth7** [comment]
You mean, if there's no favicon available? Looks like in issue with tt-rss itself to me, since this also happens in the default theme.

**Comment by maxfragg** [comment]
no, not only for favicons, see your threat in the ttrss forums (including screenshot of the bug)
http://tt-rss.org/forum/viewtopic.php?f=22&t=2247&start=45

**Comment by naeramarth7** [comment]
Thanks for the link - did not get a notification for the new post.

The issue in the mentioned post (and screenshot) was not an issue with the theme itself, but with IIS.
Any chance you got your ttrss installed on IIS? Then you may need map the .otf file extension in IIS. This solved Gizmoh's problem.

See: http://big.info/2013/06/how-to-use-otf-opentype-format-fonts-on.html
